/************************************************
Treehouse Techdegree:
Project 4 - Random Quote Generator
*************************************************/

// For assistance: 
  // Check the "Project Resources" section of the project instructions
  // Reach out in your Slack community

/*** 
 * `quotes` array. 7 objects in which4 have citation and year, and 3 do not have them.
***/
const quotes = [
  {
    quote: 'Life is what happens when you’re busy making other plans.',
    source: 'John Lennon',
    citation: 'Double Fantasy',
    year: '1980',
    genre: 'Rock'
  },
  {
    quote: 'Works of art make rules; rules do not make works of art.',
    source: 'Claude Debussy',
    // citation: 'Companion to Contemporary Musical Thought',
    // year: '1992'
  },
  {
    quote: 'One should either be a work of art, or wear a work of art.',
    source: 'Oscar Wilde',
    citation: 'The Soul of Man under Socialism',
    year: '1891'

  },
  {
    quote: 'Melody is the essence of music.',
    source: 'Wolfgang Amadeus Mozart',
    citation: 'Reminiscences of Michael Kelly',
    year: '1826'
  },
  {
    quote: 'For me, music and life are al about style.',
    source: 'Miles Davis',
    // citation: 'Miles, the Autobiography',
    // year: '1989'
  },
  {
    quote: 'My music is best understood by children and animals',
    source: 'Igor Stravinsky',
    citation: 'The Observer',
    year: '1961',
    genre: 'Classical' //added genre property to meet exceeds expectations.
  },
  {
    quote: 'The song is the center; the song is the key.',
    source: 'Carole King',
    // citation: 'The Birmingham Post',
    // year: '2001'
  }
];

/***
 * `getRandomQuote` function
***/

function getRandomQuote () {
  const randomNumber = Math.floor( Math.random() * quotes.length ); //a random number is generated by using the math.random method and multiplied by the length of the objects in the array.
  // console.log(randomNumber);
  let result = quotes[randomNumber];
  // console.log(result);
  return result;
}

//This Function changes the background color of the body element. It is called in the printQuote function.
function randomColor () {
  const random = () => Math.floor(Math.random() * 256); //got this arrow function from the functions module in treehouse.
  let randomRGB = `rgb(${random()}, ${random()}, ${random()})`;

  document.body.style.backgroundColor = randomRGB;
}

/***
 * `printQuote` function
 * Function takes the random object returned from getRandomQuote and stores it in a variable.
 * Then a variable named is html holds two html p elements that hold the quote and source property from the
 * random object.
 * Then two if statements check for a citation and year property on the object,
 * and if they exist it adds it to the html variable.
 * Then the final html string is added to the inner html of the element with quote-box id.
***/

function printQuote () {
  let randomQuote = getRandomQuote()
  let html = `
    <p class="quote"> ${randomQuote.quote} </p>
    <p class="source"> ${randomQuote.source} 
  `;
  if (randomQuote.citation) {
    html += `
      <span class="citation"> ${randomQuote.citation} </span>
    `;
  }
  if (randomQuote.year) {
    html += `
      <span class="year"> ${randomQuote.year} </span>
    `;
  }
  if (randomQuote.genre) {
    html += `
      <span class="year"> ${randomQuote.genre} </span>
    `;
  }
  html += `</p>`
  document.getElementById('quote-box').innerHTML = html;
  randomColor();
}


/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
***/

document.getElementById('load-quote').addEventListener("click", printQuote, false);
setInterval(printQuote, 10000); //changes the background color every 10 seconds.